@WebStore.API_HostAddress = https://localhost:7020

GET {{WebStore.API_HostAddress}}/api/webstore

###

@id = 96e02e86-3f2e-49c5-a09f-e5eaea370345
GET {{WebStore.API_HostAddress}}/api/webstore/{{id}}

###

