@WebStore.API_HostAddress = https://localhost:7020

GET {{WebStore.API_HostAddress}}/api/webstore

###

@id = 96e02e86-3f2e-49c5-a09f-e5eaea370345
GET {{WebStore.API_HostAddress}}/api/webstore/{{id}}

###


POST {{WebStore.API_HostAddress}}/api/webstore
Content-Type: application/json

{
    "name": "Night Dream BooksStore",
    "description": "Your every night book reading.",
    "hasDelivery": false,
    "address": {
      "city": "Atlanta",
      "street": "28 Cool Reading Rd",
      "postalCode": "34875"
    },
    "contactPhoneNumber": "555-3366",
    "contactEmail": "readers@ndb.shop",
    "extraInfo": "",
    "websiteUrl": "https://www.ndb.shop"
}

###

PUT {{WebStore.API_HostAddress}}/api/webstore
Content-Type: application/json

{
    "id": "08786b5c-d700-4fdc-a187-e06c2f156b65",
    "name": "Night Dream BooksStore",
    "description": "Your every night book reading.",
    "hasDelivery": false,
    "address": {
      "id": "8c4a9b3c-5446-4143-b204-98ae2b9f9891",
      "city": "Atlanta",
      "street": "28 Cool Reading Rd",
      "postalCode": "64887"
    },
    "contactPhoneNumber": "555-3366",
    "contactEmail": "readers@ndb.shop",
    "extraInfo": "",
    "websiteUrl": "https://www.ndb.shop",
    "products": []
  }

###

@id = f33809e6-7183-4888-b4c3-e1d3791405f6
DELETE {{WebStore.API_HostAddress}}/api/webstore/{{id}}

###

@webStoreId = 96e02e86-3f2e-49c5-a09f-e5eaea370345
GET {{WebStore.API_HostAddress}}/api/product/{{webStoreId}}/products

###

@webStoreId = 96e02e86-3f2e-49c5-a09f-e5eaea370345
@productId = a7fc3ddb-dcb3-457e-9063-8e88d8ba20ac
GET {{WebStore.API_HostAddress}}/api/product/{{webStoreId}}/products/{{productId}}

###

@webStoreId = 96e02e86-3f2e-49c5-a09f-e5eaea370345
POST {{WebStore.API_HostAddress}}/api/product/{{webStoreId}}/products
Content-Type: application/json

{
  "webStoreId": "96e02e86-3f2e-49c5-a09f-e5eaea370345",
  "name": "Honor 200",
  "description": "New top brand for smartphones",
  "price": 259.99,
  "categoryId": "ab3100ea-74aa-4d04-ae76-0473dd88108c",
  "brandId": "1d215ed0-af6f-4f59-a0a7-f08312417a03",
  "model": "200-S7G312512",
  "imageUrl": "https://example.com/honor200.jpg"
}

###

@webStoreId = 96e02e86-3f2e-49c5-a09f-e5eaea370345
PUT {{WebStore.API_HostAddress}}/api/product/{{webStoreId}}/products/9130e08c-820e-4698-a6ad-02ffd3be3925
Content-Type: application/json

{
  "webStoreId": "96e02e86-3f2e-49c5-a09f-e5eaea370345",
  "id": "9130e08c-820e-4698-a6ad-02ffd3be3925",
  "name": "Honor 200",
  "description": "New top brand for smartphones",
  "price": 269.99,
  "categoryId": "ab3100ea-74aa-4d04-ae76-0473dd88108c",
  "brandId": "1d215ed0-af6f-4f59-a0a7-f08312417a03",
  "model": "200-S7G312512",
  "imageUrl": "https://example.com/honor200-200-S7G312512.jpg"
}

###
